### Lab #2:

In [1]:
from sklearn import datasets

In [2]:
#student index number = 10
n_rows = 100000
n_cols = 30-10

### make_regression():

In [3]:
data = datasets.make_regression(
    n_samples=n_rows, #the number of samples (rows)
    n_features=n_cols, #the number of features (X-columns)
    n_informative=int(n_cols/2), # the number of features used to build the linear model (to generate the output)
    n_targets = int(n_cols/n_cols), #the dimension of the y output vector
    bias=150,
    effective_rank = None, #the input set is well conditioned, centered and gaussian with unit variance
    tail_strength = 0.7, #the relative importance of the fat noisy tail of the singular values profile
    noise = 0.9, #the standard deviation of the gaussian noise applied to the output
    shuffle = True,
    coef = False,
    random_state=42)

### Data:

In [4]:
import pandas as pd
df = pd.DataFrame(data[0])
df = df.add_prefix('x') #adding prefix to column names
df['y'] = data[1]
df.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x11,x12,x13,x14,x15,x16,x17,x18,x19,y
0,-0.570570,-0.135807,0.180026,0.027711,1.940470,-0.412001,-1.201978,0.710082,0.258933,0.876241,...,0.689736,0.345990,1.330182,0.462611,1.384081,-0.109851,-0.879700,-0.464504,0.069444,201.140354
1,-1.053366,0.700219,1.367012,-0.209251,-0.419151,0.919912,1.182189,-1.602707,0.875555,0.070295,...,-1.631898,0.149233,0.025009,0.541971,0.236379,-0.778615,1.062795,-0.727257,-0.690700,224.262602
2,0.624803,-0.317113,-1.810684,-0.972827,0.118465,0.867733,-1.141269,0.096091,-0.694285,0.306378,...,0.132128,0.877367,-0.678331,-0.106104,1.252914,-1.929616,-0.327504,-0.424509,-0.775117,-120.508389
3,1.148335,0.378181,-1.851080,0.847433,-1.108134,-1.632174,0.939754,0.093289,0.304182,-1.230486,...,1.690947,-1.090418,1.072004,1.022756,-0.220791,-1.495709,-0.496876,0.288404,0.698676,24.357698
4,0.311175,0.178473,0.317134,1.475777,-0.001404,0.746224,-1.889903,-0.618845,-0.237277,0.179813,...,1.092546,0.998532,0.417531,-1.677472,-1.120176,0.648240,-1.164220,-0.693127,1.597735,184.667199

In [5]:
df.to_csv('data/data.csv', sep=';', index=False)